---

---

## Exercise solutions

===

### Solution 1

```{r}
filenames <- glue::glue("{unique(pg_df$Island)}.csv")
pg_df %>% 
  group_split(Island) %>% 
  walk2(filenames, ~write_csv(.x, .y))
```

[Return](#exercise-1)
{:.notes}

### Solution 2

```{r}
pg_df$filename %>% 
  fs::as_fs_path() %>%
  fs::path_ext_remove() %>%
  fs::path_file()
```

[Return](#exercise-2)
{:.notes}

### Solution 3

```{r}
pg_df %>%
  mutate(species = glue("{common}<br><i style='color:{color}'>({latin})</i>")) %>%
  ggplot(aes(x = species, y = delta_13_c_ooo)) +
  geom_boxplot(aes(fill = color), alpha = 0.75) + 
  scale_fill_identity() + # tricky! 
  coord_flip() +
  theme(axis.text.y = element_markdown())
```

[Return](#exercise-3)
{:.notes}

### Solution 4

```{r}
pg_df %>% 
  ggplot(aes(x = common, y = delta_13_c_ooo)) +
  geom_boxplot() + coord_flip() +
  theme(axis.text.y = element_markdown()) +
  ylab(expression(paste(delta^13, "C (\u2030)")))
```

[Return](#exercise-4)
{:.notes}

### Solution 5

```{r}
pg_df %>% 
  mutate(across(where(is.character) & !contains("comment"), as_factor))
```

[Return](#exercise-4)
{:.notes}

### Solution 6

```{r}
library(magrittr)
model_names <- glue("model_{letters[1:10]}")
pars %<>% crossing(model_names)
```

[Return](#exercise-6)
{:.notes}