---
---

## What is the tidyverse? 

The [tidyverse](https://www.tidyverse.org/) is an "opinonated collected of R packages designed for data science." There are multiple packages designed to tackle each stage of the data science workflow (importing, transforming, visualizing, modeling, etc.). All of the packages are unified by common design philosophies and data structures. 
{:.notes}

set of packages that share a high-level design philosophy and low-level grammar and data structures, so that learning one package makes it easier to learn the next

alternatives: base R, which prioritizes stability, and data.table which prioritizes concision and performance

===

## Core Tidyverse

Load the tidyverse meta-package using:

```{r library, handout = 0}
library(tidyverse)
```

These are the 8 packages now loaded into your environment:

| Package    | Purpose                       |
|------------+-------------------------------|
| `readr`    |  read flat files              |
| `tidyr`    |  reshaping                    |
| `dplyr`    |  wrangling                    |
| `ggplot2`  |  visualization                |
| `stringr`  | control character vectors     |
| `tibble`   | opinionated data frames       |
| `forcats`  | control categorical data      |
| `purrr`    | functional programming        |

===

## Expanded tidyverse

What took so long to install then? `install.packages("tidyverse")` also installs these 15 other packages:

| Package    | Purpose                       |
|------------+-------------------------------|
| `broom`     |                |
| `dbplyr`    |                      |
| `haven`     |                      |
| `hms`       |                  |
| `httr`      |      |
| `jsonlite`  |        |
| `lubridate` |       |
| `magrittr`  |         |
| `modelr`    | |
| `pillar`    | |
| `readxl`    | |
| `reprex`    | |
| `rlang`     | |
| `rvest`     | |
| `xml2`      | |

and their 66 dependencies including `fs`, `glue`, and `scales` which we will use in this lesson.

===

